require "csv"
require "json"
require "combine/input_parser"
require "combine/input_parser/articles_parser"
require "combine/input_parser/authors_parser"
require "combine/input_parser/journals_parser"
require "combine/formatter/json_formatter"
require "combine/formatter/csv_formatter"
require "combine/record"
require "combine/base"

require "combine/exceptions"
require "pry-byebug"
